/**
 * Release history shown in Settings → Changelog.
 *
 * Source of truth is the root CHANGELOG.md, which is regenerated by the
 * release pipeline from conventional commits on every push to master.
 * Vite's `?raw` import inlines the markdown into the bundle at build time,
 * so the Settings UI is always in lock-step with the actually-shipped
 * version of the app — no manual editing required when a release ships.
 */
import RAW from '../../CHANGELOG.md?raw'

/**
 * @param {string} md  raw CHANGELOG.md contents
 * @returns {Array<{version: string, date: string, title: string, highlights: string[]}>}
 */
function parseChangelog(md) {
  if (!md) return []
  const entries = []
  let current = null

  // Match section headers: `## v1.2.3 — 2026-06-06` or `## v1.2.3 - Title`.
  const versionLine = /^##\s+v?(?<version>\d+\.\d+\.\d+(?:[-+][\w.]+)?)\s*[—-]\s*(?<rest>.+)$/i
  const bulletLine = /^[-*]\s+(?<text>.+)$/

  for (const raw of md.split(/\r?\n/)) {
    const line = raw.trim()
    if (!line) continue

    const v = line.match(versionLine)
    if (v) {
      if (current) entries.push(current)
      const rest = v.groups.rest.trim()
      // If the "rest" looks like an ISO date, treat it as the date and use a
      // generated title; otherwise use it as the title with no explicit date.
      const isDate = /^\d{4}-\d{2}-\d{2}/.test(rest)
      current = {
        version: v.groups.version,
        date: isDate ? rest : '',
        title: isDate ? '' : rest,
        highlights: [],
      }
      continue
    }

    if (current) {
      const b = line.match(bulletLine)
      if (b) {
        // Drop short-hash suffixes like "(abc1234)" — they're noise in the UI.
        const text = b.groups.text.replace(/\s*\([0-9a-f]{6,40}\)\s*$/, '').trim()
        if (text) current.highlights.push(text)
      }
    }
  }
  if (current) entries.push(current)
  return entries
}

const parsed = parseChangelog(RAW)

// Fallback: if the markdown parse fails or is empty, fall back to the manual
// seed so the Settings UI never shows blank.
export const CHANGELOG = parsed.length > 0
  ? parsed
  : [
      {
        version: '1.0.0',
        date: 'June 2026',
        title: 'Initial public release',
        highlights: [
          'Universal Dynamic Island for Pomodoro, hydration, sync, and progress',
          'Chrono-adaptive day/night theming with dynamic mode accents',
          'Web → desktop QR sign-in gateway (Google OAuth on mobile)',
          'First-run legal acceptance + execution-scope selection',
          'Natural-language calendar capture with a live timeline flag',
          'Automated Kanban → subject syllabus progress sync',
          'Apple-style activity rings and a read-only achievement ledger',
          'Always-on focus mini-timer that follows you across modules',
          'Global hotkeys, tray background execution, hardware-bound device identity',
          'Automatic over-the-air updates',
        ],
      },
    ]
